#Listener configurations
"http":
   "host": "0.0.0.0"
   "port": "8082"
   "basepath": "/api/*"
   "config": "sitecore-sapi-listener-config"
   "timeout": "30000"
#api details
"application":
  "name":  "sitecore-integration"
  "version"     : "1"
  "instanceName": "sitecore-sapi"
  "environment": "dev"
  "status": "running"
#request configuration  
"request":
   "aurl": "http://sitecore-integration.us-e2.cloudhub.io/search"
   "lurl": "http://sitecore-integration.us-e2.cloudhub.io/entities/575365"